# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Chat-Daemon
version:      0.3
version_from: lib/Net/Chat/Daemon.pm
installdirs:  site
requires:
    Net::Jabber:                   1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
